### PR TITLE
mob.ini: fix missing remote zlib

### PR DESCRIPTION
**Pull request by nikitalita**
Bumped zlib version from 1.2.12 to 1.2.13.
1.2.12 tarball no longer exists at zlib.net

See for yourself:
https://zlib.net/zlib-1.2.12.tar.gz
https://zlib.net/zlib-1.2.13.tar.gz

### CODE REVIEW

**Comment by Holt59** [comment]
The currently active branch is the qt6 one where zlib has already been bumped to 1.2.13, you should use this branch if you want to contribute to MO2.

**Comment by Qudix** [comment]
Side note, it may be pertinent to switch to downloading from the [github repo](https://github.com/madler/zlib) rather than the website as older versions are still available on the repo.

**Comment by nikitalita** [comment]
> The currently active branch is the qt6 one where zlib has already been bumped to 1.2.13, you should use this branch if you want to contribute to MO2.

Maybe you should set that as the default branch, then?

**Comment by AnyOldName3** [comment]
I think the plan's to merge it. I'm not entirely sure why that's not been done as I think we think everything's working.

**Pull request closed without merging**
